export type Language = "en" | "zh";

export const copy = {
  en: {
    languageName: "中文",
    studio: {
      label: "Studio studies", title: "Stone, suspended. Light, settled.",
      note: "Three companion studies in stone, water and weather. Separate explorations alongside the original pair of paintings.",
      stair: "Basalt Stair", stairCaption: "A broken ascent held above the mist.", stairAlt: "Ink-blue basalt steps climb a suspended stone spine above pale mist",
      inlet: "Mineral Inlet", inletCaption: "Pale shore, floating stone, a quiet horizon.", inletAlt: "A curved pale mineral shore surrounds still water beneath sparse floating rocks",
      reeds: "Stone and Reeds", reedsCaption: "Weather gathers at the edge of stone.", reedsAlt: "Weathered stone and slender reeds face a distant suspended ruin in mist",
      browse: "Explore the studio studies", reading: "Close reading", gate: "The ruin stays in place.",
      gateBody: "Matched details from the original paintings: the same stone, the same crop, two states of light.",
      darkDetail: "Original detail · shadow", lightDetail: "Original detail · light",
      darkAlt: "Close crop of the original ruined gate and cliff in blue shadow", lightAlt: "Matching close crop of the original gate and cliff in warm light",
    },
    skip: "Skip to exhibition content",
    nav: { home: "Exhibition", works: "Works", about: "About" },
    maker: "An interactive work by PACHIN",
    home: {
      title: "INK WORLDS",
      subtitle: "A landscape held between two states of light.",
      hint: "Move to uncover the image beneath",
      touchHint: "Drag to uncover the image beneath",
      reducedHint: "Choose Dark or Light",
      statementKicker: "Digital exhibition · 01",
      statementTitle: "One place. Two ways of seeing.",
      statementBody: "Ink Worlds treats light as a hidden layer rather than an effect. The same painted terrain remains aligned while a fading brush opens brief passages between dusk and day.",
      comparisonTitle: "A horizon changes without moving.",
      darkCaption: "Outer world · held in ink-blue shadow",
      lightCaption: "Inner world · released into warm light",
      entryKicker: "Featured work",
      entryTitle: "Two Worlds",
      entryBody: "Enter the full viewing surface, then follow the making process from paired paintings to an impermanent digital brush.",
      enter: "View the work",
      processKicker: "Process fragment",
      processTitle: "The brush reveals; it does not repaint.",
      processBody: "Each mark removes a temporary portion of the dark layer. The bright image beneath stays untouched, shares the same crop, and fades from view as the mark dissolves.",
      credits: "Original paintings and interaction concept by PACHIN. Exhibition frontend expanded from the owner-supplied motion preview.",
    },
    controls: { dark: "Dark", reveal: "Reveal", light: "Light", pause: "Pause", play: "Play", retry: "Retry artwork", group: "Scene controls" },
    sceneLabel: "Interactive painting. Move the pointer, drag on touch, or use arrow keys to reveal the second layer.",
    outerAlt: "Dark floating landscape with a ruined gate above a sea of clouds",
    innerAlt: "Sunlit version of the same floating landscape and aligned ruined gate",
    works: {
      eyebrow: "Catalogue",
      title: "One work, observed three ways.",
      intro: "The catalogue stays close to a single landscape. Two viewing studies isolate its states of light; the complete work holds them together through interaction.",
      complete: "Complete interactive work",
      completeTitle: "Two Worlds",
      completeBody: "A paired landscape revealed through a fading digital brush.",
      study: "Viewing study",
      darkTitle: "Two Worlds — Night Field",
      darkBody: "The outer painting studied as a still field of distance, weather and suspended stone.",
      lightTitle: "Two Worlds — Day Field",
      lightBody: "The aligned inner painting studied for warm atmosphere, opened cloud and returned detail.",
      open: "Open work",
      footer: "All entries belong to the same artwork; the two studies are not separate works.",
    },
    detail: {
      back: "Back to works",
      eyebrow: "Interactive work · 2026",
      title: "Two Worlds",
      intro: "A floating landscape exists in two synchronized states. Move across the image to let one world surface through the other; stop, and the opening closes.",
      surfaceTitle: "Viewing surface",
      surfaceNote: "Pointer, touch and arrow keys are supported. The temporary brush trail fades naturally.",
      processEyebrow: "Process",
      processTitle: "Two paintings, one coordinate system.",
      processBody1: "The dark and light paintings have identical dimensions and composition. Both use the same cover calculation, so a gate, cliff or cloud remains fixed when the layer changes.",
      processBody2: "The Canvas carries only an alpha mask. It copies the dark painting, then erases irregular brush marks to expose the light painting already placed beneath it.",
      studiesTitle: "Light-state studies",
      darkStudy: "Night field",
      lightStudy: "Day field",
      darkStudyBody: "Compressed values draw attention to depth, weather and the silhouette of the suspended terrain.",
      lightStudyBody: "Warm sky and luminous cloud return color to the same stones without changing their position.",
      creditsTitle: "Credits",
      creditsBody: "Original artwork, interaction concept and source preview: PACHIN. Exhibition design and frontend expansion created from the supplied source. Typeface licenses are included with the project assets.",
    },
    about: {
      eyebrow: "About the exhibition",
      title: "Interaction as a way of looking.",
      intro: "Ink Worlds is a small digital exhibition built around the act of uncovering one image inside another.",
      approachTitle: "Visual approach",
      approachBody: "The work combines an ink-blue atmosphere, floating terrain and warm paper spaces. The exhibition framing stays quiet so the landscape remains the main source of scale and mystery.",
      interactionTitle: "Interaction approach",
      interactionBody: "The reveal behaves like an impermanent brush. It is local, irregular and fading: enough to compare two states, never enough to turn the image into a permanent collage.",
      makerTitle: "Maker credit",
      makerBody: "PACHIN is credited as the maker of the original paintings and interactive concept. This exhibition does not add a fictional biography, awards or exhibition history.",
      sourceTitle: "Source continuity",
      sourceBody: "The original two-layer composition, brush mask, controls and exploration methods remain at the center of the expanded experience.",
    },
    footer: { title: "Ink Worlds", line: "Digital exhibition · PACHIN", top: "Back to top" },
  },
  zh: {
    languageName: "EN",
    studio: {
      label: "创作习作", title: "石悬于空，光落于岸。",
      note: "石、水与风雨的三组习作。与原来的两张画并置，作为独立的场景探索。",
      stair: "玄武岩阶", stairCaption: "断续的阶梯，悬于雾上。", stairAlt: "墨蓝色玄武岩阶沿悬浮岩脊攀升，下方是浅色云雾",
      inlet: "矿色水湾", inletCaption: "浅岸、浮石与安静的地平线。", inletAlt: "浅色矿岩岸线环绕静水，远处零星岩石悬浮",
      reeds: "石与苇", reedsCaption: "风雨的痕迹，停留在石缘。", reedsAlt: "风化岩石与纤细芦苇面向雾中远处的悬浮残筑",
      browse: "浏览创作习作", reading: "细读画面", gate: "残筑的位置未曾改变。",
      gateBody: "取自原始绘画的对应细节：同一块石、同一处裁切，两种光线状态。",
      darkDetail: "原作局部 · 阴影", lightDetail: "原作局部 · 日光",
      darkAlt: "原作残破石门与悬崖的墨蓝阴影局部", lightAlt: "原作同一石门与悬崖在温暖日光下的对应局部",
    },
    skip: "跳至展览内容",
    nav: { home: "展览", works: "作品", about: "关于" },
    maker: "PACHIN 互动作品",
    home: {
      title: "水墨世界",
      subtitle: "一片风景，悬停于两种光线之间。",
      hint: "移动指针，揭开下方的景象",
      touchHint: "拖动以揭开下方的景象",
      reducedHint: "选择暗部或亮部",
      statementKicker: "数字展览 · 01",
      statementTitle: "同一处境地，两种观看方式。",
      statementBody: "《水墨世界》将光视为隐藏的图层，而非附加效果。两幅画的地形始终对齐，一支渐隐的笔刷在暮色与白昼之间短暂开路。",
      comparisonTitle: "地平线未动，世界已经改变。",
      darkCaption: "外部世界 · 沉入墨蓝色阴影",
      lightCaption: "内部世界 · 释放于温暖日光",
      entryKicker: "焦点作品",
      entryTitle: "双重世界",
      entryBody: "进入完整的观看界面，再沿着创作过程，了解成对绘画如何成为一支短暂存在的数字笔刷。",
      enter: "观看作品",
      processKicker: "过程片段",
      processTitle: "笔刷负责揭示，而不是重绘。",
      processBody: "每一道笔触只会暂时移除暗色图层。下方的亮色图像保持原貌，使用相同裁切，并随着笔触消散而重新隐去。",
      credits: "原始绘画与交互构想：PACHIN。本展览前端由版权所有者提供的动态预览扩展而成。",
    },
    controls: { dark: "暗部", reveal: "揭示", light: "亮部", pause: "暂停", play: "继续", retry: "重试画面", group: "场景控制" },
    sceneLabel: "交互式绘画。移动指针、触摸拖动或使用方向键，揭示第二层图像。",
    outerAlt: "云海上方带有残破石门的暗色悬浮景观",
    innerAlt: "同一悬浮景观与石门对齐的日照版本",
    works: {
      eyebrow: "作品目录",
      title: "一件作品，三种观看方式。",
      intro: "目录始终围绕同一片风景。两项观看习作分别呈现它的明暗状态；完整作品则通过互动让两者相遇。",
      complete: "完整互动作品",
      completeTitle: "双重世界",
      completeBody: "通过渐隐数字笔刷显现的成对风景。",
      study: "观看习作",
      darkTitle: "双重世界——夜之场",
      darkBody: "将外部绘画作为静态场域，观察距离、天气与悬浮岩体。",
      lightTitle: "双重世界——昼之场",
      lightBody: "观察对齐的内部绘画如何以温暖空气、开阔云层与重现的细节回应暗部。",
      open: "打开作品",
      footer: "所有条目均属于同一件作品；两项习作并非独立作品。",
    },
    detail: {
      back: "返回作品",
      eyebrow: "互动作品 · 2026",
      title: "双重世界",
      intro: "一片悬浮风景同时存在于两种同步状态。移动于画面之上，让一个世界从另一个世界中浮现；停下时，开口便逐渐合拢。",
      surfaceTitle: "观看界面",
      surfaceNote: "支持指针、触摸与方向键。短暂的笔刷轨迹会自然淡去。",
      processEyebrow: "创作过程",
      processTitle: "两幅绘画，共用一套坐标。",
      processBody1: "暗部与亮部绘画拥有相同尺寸与构图，并采用同一套覆盖计算，因此石门、悬崖与云层在图层变化时始终固定。",
      processBody2: "画布只承载透明度遮罩：先复制暗部绘画，再用不规则笔触将其擦除，显露已经放置在下方的亮部绘画。",
      studiesTitle: "光线状态习作",
      darkStudy: "夜之场",
      lightStudy: "昼之场",
      darkStudyBody: "压缩的明暗关系让距离、天气与悬浮地形的轮廓更加突出。",
      lightStudyBody: "温暖天空与明亮云层让色彩重回同一组岩石，却不改变它们的位置。",
      creditsTitle: "创作信息",
      creditsBody: "原始绘画、交互构想与源预览：PACHIN。展览设计与前端扩展以提供的源文件为基础。字体许可随项目资源一并保留。",
    },
    about: {
      eyebrow: "关于展览",
      title: "将互动作为一种观看方式。",
      intro: "《水墨世界》是一场小型数字展览，围绕从一幅图像中揭开另一幅图像的动作展开。",
      approachTitle: "视觉方法",
      approachBody: "作品结合墨蓝色氛围、悬浮地形与暖纸色空间。展览框架保持安静，让风景继续成为尺度感与神秘感的主要来源。",
      interactionTitle: "交互方法",
      interactionBody: "揭示效果如同一支短暂存在的笔刷：局部、不规则、逐渐消退。它足以比较两种状态，却不会把图像变成永久拼贴。",
      makerTitle: "创作者署名",
      makerBody: "PACHIN 作为原始绘画与交互构想的创作者署名。本展览不添加虚构的个人经历、奖项或展览历史。",
      sourceTitle: "源作延续",
      sourceBody: "原始双层构图、笔刷遮罩、控制方式与探索方法，仍然是扩展体验的核心。",
    },
    footer: { title: "水墨世界", line: "数字展览 · PACHIN", top: "返回顶部" },
  },
} as const;
